# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-22 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0015_auto_20180508_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tnrevent',
            name='location',
        ),
        migrations.AlterField(
            model_name='tnrapplication',
            name='cats_feeding',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Who feeds the cats? What time are they normally fed? Morning/evening? What time?'),
        ),
    ]
