# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-22 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0016_auto_20180621_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnrevent',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='events', to='tnr.TNRLocation'),
        ),
    ]
