# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tnr.TNRApplication')),
            ],
        ),
        migrations.AlterField(
            model_name='tnrlocation',
            name='notes_private',
            field=models.TextField(blank=True, verbose_name='Private Notes. (Not to be shared with CP.)'),
        ),
        migrations.AlterField(
            model_name='tnrlocation',
            name='notes_public',
            field=models.TextField(blank=True, verbose_name='Public Notes'),
        ),
    ]
