# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trap',
            name='cat_desc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trap',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unknown')], default='Unk', max_length=1),
        ),
        migrations.AlterField(
            model_name='trap',
            name='status',
            field=models.CharField(blank=True, choices=[('Itk', 'Intake'), ('Dec', 'Deceased'), ('Rel', 'Released to Colony'), ('Oth', 'Other'), ('Unk', 'Unknown')], default='Unk', max_length=3),
        ),
        migrations.AlterField(
            model_name='trap',
            name='trap_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
