# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0002_auto_20171121_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tnrapplication',
            name='add_info',
            field=models.TextField(blank=True, null=True, verbose_name='Is there any additional information which would helpful?'),
        ),
        migrations.AlterField(
            model_name='tnrapplication',
            name='cats_feeding',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Who feeds the cats? What time are they normally fed (morning/evening)?'),
        ),
        migrations.AlterField(
            model_name='tnrapplication',
            name='cats_fixed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Do you know if any of the cats are already fixed?'),
        ),
        migrations.AlterField(
            model_name='tnrapplication',
            name='cats_friendly',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Are any of the cats friendly? Can you touch them?'),
        ),
        migrations.AlterField(
            model_name='tnrapplication',
            name='cats_pregnant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Do you know if any of the cats are currently pregnant?'),
        ),
        migrations.AlterField(
            model_name='tnrapplication',
            name='cats_total',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='How many cats total (including kittens)?'),
        ),
        migrations.AlterField(
            model_name='tnrapplication',
            name='colony_city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='What city is the colony located?'),
        ),
        migrations.AlterField(
            model_name='tnrapplication',
            name='colony_cross_streets',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='What are the major cross streets nearest the colony?'),
        ),
        migrations.AlterField(
            model_name='tnrapplication',
            name='colony_state',
            field=models.CharField(blank=True, default='CA', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tnrapplication',
            name='colony_street_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='What is the street address for the colony?'),
        ),
        migrations.AlterField(
            model_name='tnrapplication',
            name='colony_zipcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='What is the zip code where the colony is located?'),
        ),
        migrations.AlterField(
            model_name='tnrapplication',
            name='contact_city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='What is your home city?'),
        ),
        migrations.AlterField(
            model_name='tnrapplication',
            name='contact_phone_cell',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='What is your cell phone number?'),
        ),
        migrations.AlterField(
            model_name='tnrapplication',
            name='contact_phone_land',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='What is your home telephone number?'),
        ),
        migrations.AlterField(
            model_name='tnrapplication',
            name='contact_state',
            field=models.CharField(blank=True, default='CA', max_length=2, null=True, verbose_name='What state do you live in?'),
        ),
        migrations.AlterField(
            model_name='tnrapplication',
            name='contact_street_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='What is your home street address?'),
        ),
        migrations.AlterField(
            model_name='tnrapplication',
            name='contact_zipcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='What is your home zip code?'),
        ),
        migrations.AlterField(
            model_name='tnrapplication',
            name='kittens_total',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='How many kittens are there? What is their approximate age?'),
        ),
        migrations.AlterField(
            model_name='tnrapplication',
            name='location_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Please describe the colony location. Is it a business/home/school/field/or ...'),
        ),
        migrations.AlterField(
            model_name='tnrapplication',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Private KB Notes about location.'),
        ),
        migrations.AlterField(
            model_name='tnrapplication',
            name='scheduling_issues',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='The community partner needs to be present to show us where the cats hang out. Are there any scheduling issues?'),
        ),
        migrations.AlterField(
            model_name='tnrapplication',
            name='transportation',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Do you have a car or other transportation to help with taking the cats to/from the vet?'),
        ),
        migrations.AlterField(
            model_name='tnrevent',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tnrevent',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Long Description'),
        ),
        migrations.AlterField(
            model_name='tnrevent',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='tnrleg',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tnrleg',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tnrlocation',
            name='colony_address01',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tnrlocation',
            name='colony_address02',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tnrlocation',
            name='colony_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tnrlocation',
            name='colony_zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tnrlocation',
            name='cp_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tnrlocation',
            name='cp_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tnrlocation',
            name='cp_telephone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tnrlocation',
            name='notes_private',
            field=models.TextField(blank=True, null=True, verbose_name='Private Notes. (Not to be shared with CP.)'),
        ),
        migrations.AlterField(
            model_name='tnrlocation',
            name='notes_public',
            field=models.TextField(blank=True, null=True, verbose_name='Public Notes'),
        ),
        migrations.AlterField(
            model_name='tnrrole',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trap',
            name='cat_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trap',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unknown')], default='U', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='trap',
            name='status',
            field=models.CharField(blank=True, choices=[('I', 'Intake'), ('D', 'Deceased'), ('R', 'Released to Colony'), ('O', 'Other'), ('U', 'Unknown')], default='U', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='trap',
            name='trap_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
