# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0002_auto_20171115_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appstatus',
            name='status',
        ),
        migrations.AddField(
            model_name='appstatus',
            name='app_status',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tnrapplication',
            name='app_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tnr.AppStatus'),
        ),
    ]
