# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0003_auto_20171125_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnrapplication',
            name='app_status',
            field=models.CharField(choices=[('B', 'Banned'), ('C', 'Closed'), ('I', 'In Progress'), ('N', 'New Contact'), ('O', 'Out of Area'), ('P', 'Pending'), ('S', 'Self Trapping')], default='N', max_length=1),
        ),
    ]
