# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0003_auto_20171115_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnrapplication',
            name='app_status',
            field=models.CharField(choices=[('B', 'Banned'), ('I', 'In Progress'), ('O', 'Out of Area'), ('C', 'Closed'), ('S', 'Self Trapping')], default='I', max_length=1),
        ),
        migrations.DeleteModel(
            name='AppStatus',
        ),
    ]
