# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0004_auto_20171125_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='trap',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tnr.TNRRole'),
        ),
        migrations.AlterField(
            model_name='tnrrole',
            name='leg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tnr.TNRLeg'),
        ),
        migrations.AlterField(
            model_name='trap',
            name='status',
            field=models.CharField(blank=True, choices=[('I', 'Intake'), ('H', 'Homeschool'), ('D', 'Deceased'), ('R', 'Released to Colony'), ('O', 'Other'), ('U', 'Unknown')], default='U', max_length=1, null=True),
        ),
    ]
