# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0005_auto_20171211_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tnrlocation',
            name='event',
        ),
        migrations.RemoveField(
            model_name='trap',
            name='location',
        ),
        migrations.AddField(
            model_name='tnrevent',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tnr.TNRLocation'),
        ),
        migrations.AddField(
            model_name='trap',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tnr.TNREvent'),
        ),
    ]
