# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0006_auto_20171116_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trap',
            name='location',
        ),
        migrations.AddField(
            model_name='tnrlocation',
            name='trap_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tnr.Trap'),
            preserve_default=False,
        ),
    ]
