# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0006_auto_20171218_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tnrevent',
            name='location',
        ),
        migrations.AddField(
            model_name='tnrevent',
            name='location',
            field=models.ManyToManyField(blank=True, to='tnr.TNRLocation'),
        ),
    ]
