# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0007_auto_20171218_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnrevent',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='events', to='tnr.TNRLocation'),
        ),
    ]
