# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0008_remove_tnrlocation_trap_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnrlocation',
            name='trap_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tnr.Trap'),
            preserve_default=False,
        ),
    ]
