# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0008_auto_20171218_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tnrlocation',
            name='date_sched',
        ),
        migrations.RemoveField(
            model_name='tnrlocation',
            name='notes_private',
        ),
        migrations.AddField(
            model_name='tnrlocation',
            name='loc_status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='O', max_length=1),
        ),
    ]
