# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0009_tnrlocation_trap_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnrlocation',
            name='date_sched',
            field=models.DateField(blank=True, default='2000-1-1'),
        ),
        migrations.AlterField(
            model_name='trap',
            name='trap_no',
            field=models.CharField(max_length=20),
        ),
    ]
