# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0010_auto_20171219_0104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tnrevent',
            options={'ordering': ('name',)},
        ),
    ]
