# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0012_auto_20171219_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnrapplication',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='What is your occupation?'),
        ),
    ]
