# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0013_tnrapplication_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnrapplication',
            name='outcome_status',
            field=models.CharField(blank=True, choices=[('Banned', 'Banned'), ('No Action', 'Closed-No Action'), ('Location Closed', 'Location Closed'), ('Out of Area', 'Out of Area'), ('Self-Trapping', 'Self Trapping')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tnrapplication',
            name='app_status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('In Progress', 'In Progress'), ('New Contact', 'New Contact'), ('Pending', 'Pending')], default='New Contact', max_length=15),
        ),
    ]
