# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0013_tnrlocation_date_sched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnrlocation',
            name='date_sched',
            field=models.DateField(blank=True),
        ),
    ]
