# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-09 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0014_auto_20180115_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnrapplication',
            name='hh_income',
            field=models.CharField(blank=True, choices=[('24', 'Below 24,000'), ('35', 'Between 24,000 and 35,000'), ('65', 'Between 35,000 and 65,000'), ('99', 'Above 65,000')], max_length=2, null=True, verbose_name='What is your household income?'),
        ),
        migrations.AlterField(
            model_name='tnrapplication',
            name='outcome_status',
            field=models.CharField(blank=True, choices=[('Banned', 'Banned'), ('No Action', 'Closed-No Action'), ('Location Closed', 'Location Closed'), ('Out of Area', 'Out of Area'), ('Self-Trapping', 'Self Trapping'), ('Scheduled', 'Scheduled'), ('Needs Flyering', 'Needs Flyering')], max_length=20, null=True),
        ),
    ]
