# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0016_auto_20171116_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tnrlocation',
            name='date_sched',
        ),
    ]
