# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0020_auto_20171116_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnrapplication',
            name='location_sched',
            field=models.ForeignKey(blank=True, default='2000-01-01', on_delete=django.db.models.deletion.CASCADE, to='tnr.TNRLocation', verbose_name='When was this application scheduled for TNR'),
        ),
    ]
