# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0023_trap_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tnrapplication',
            name='location_sched',
        ),
        migrations.RemoveField(
            model_name='tnrleg',
            name='location',
        ),
        migrations.AddField(
            model_name='tnrlocation',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tnr.TNRApplication'),
        ),
        migrations.AlterField(
            model_name='tnrapplication',
            name='cats_feeding',
            field=models.CharField(blank=True, max_length=200, verbose_name='Who feeds the cats? What time are they normally fed (morning/evening)?'),
        ),
        migrations.AlterField(
            model_name='tnrapplication',
            name='scheduling_issues',
            field=models.CharField(blank=True, max_length=200, verbose_name='The community partner needs to be present to show us where the cats hang out. Are there any scheduling issues?'),
        ),
    ]
