# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0026_auto_20171119_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tnrlocation',
            name='event',
        ),
    ]
