# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0027_remove_tnrlocation_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnrlocation',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tnr.TNREvent'),
        ),
    ]
