# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0028_tnrlocation_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnrlocation',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tnr.TNRApplication'),
        ),
        migrations.AlterField(
            model_name='tnrlocation',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tnr.TNREvent'),
        ),
    ]
