# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0029_auto_20171119_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnrlocation',
            name='date_sched',
            field=models.DateField(blank=True, null=True),
        ),
    ]
