# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0030_auto_20171119_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trap',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tnr.TNRLocation'),
        ),
    ]
