# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnr', '0031_auto_20171119_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnrapplication',
            name='app_status',
            field=models.CharField(choices=[('Ban', 'Banned'), ('Csd', 'Closed'), ('Ipr', 'In Progress'), ('NCt', 'New Contact'), ('Out', 'Out of Area'), ('Pnd', 'Pending'), ('STr', 'Self Trapping')], default='NCt', max_length=3),
        ),
        migrations.AlterField(
            model_name='trap',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unknown')], default='Unk', max_length=1),
        ),
        migrations.AlterField(
            model_name='trap',
            name='status',
            field=models.CharField(choices=[('Itk', 'Intake'), ('Dec', 'Deceased'), ('Rel', 'Released to Colony'), ('Oth', 'Other'), ('Unk', 'Unknown')], default='Unk', max_length=3),
        ),
    ]
